language: php

php:
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: 8.0

# services:

#before_install:

#install:
#  - |
#    wget https://github.com/swoole/swoole-src/archive/v4.5.2.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure && make -j$(nproc) && make install && cd - && rm -rf swoole
#    echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer update --ignore-platform-reqs --prefer-stable

script:
  - php vendor/bin/phpunit --configuration phpunit.travis.xml
